# traefik/docker-compose.yml
version: "3.8"

networks:
  traefik-public:
    name: traefik-public
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Configuration SSL avec mkcert
      - "--entrypoints.websecure.http.tls=true"
      - "--tls.certificates.default.certfile=/etc/certs/local-cert.pem"
      - "--tls.certificates.default.keyfile=/etc/certs/local-key.pem"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/certs:ro # Montage des certificats
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.local`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
